const tableData = [
  {
    sNo: 1,
    company: "A B CONSTRUCTION",
    programme: "B.Tech-Civil",
    sector: "Construction",
    studentsPlaced: 2,
    package: "3LPA",
  },
  {
    sNo: 2,
    company: "ACT 21",
    programme: "B.Tech-CSE",
    sector: "IT",
    studentsPlaced: 2,
    package: "12LPA",
  },
  {
    sNo: 3,
    company: "ALGOCIRRUS",
    programme: "B.Tech-CSE",
    sector: "IT",
    studentsPlaced: 2,
    package: "4LPA",
  },
  {
    sNo: 4,
    company: "APPSINVO PVT LTD",
    programme: "B.Tech-CSE",
    sector: "IT",
    studentsPlaced: 2,
    package: "4LPA",
  },
  {
    sNo: 5,
    company: "ASPIREFOX",
    programme: "B.Tech-CSE",
    sector: "IT",
    studentsPlaced: 2,
    package: "5LPA",
  },
  {
    sNo: 6,
    company: "AUTOMATEAZY",
    programme: "B.Tech-CSE",
    sector: "IT",
    studentsPlaced: 2,
    package: "4LPA",
  },
  {
    sNo: 7,
    company: "BETALECTIC IT PROJECTS PVT LTD.",
    programme: "BCA",
    sector: "IT",
    studentsPlaced: 5,
    package: "1.2 LPA",
  },
  {
    sNo: 8,
    company: "BISHT BROTHERS MRF TYRES",
    programme: "B.Tech-CSE",
    sector: "Manufacturing",
    studentsPlaced: 2,
    package: "4LPA",
  },
  {
    sNo: 9,
    company: "BUSINESS WEB SOLUTION",
    programme: "BCA",
    sector: "IT",
    studentsPlaced: 5,
    package: "2.2 LPA",
  },
  {
    sNo: 10,
    company: "CARTPARCEL PVT. LTD.",
    programme: "BCA",
    sector: "Marketing",
    studentsPlaced: 6,
    package: "3.5LPA",
  },
  {
    sNo: 11,
    company: "CEASEFIRE",
    programme: "B.Tech-ME",
    sector: "Marketing",
    studentsPlaced: 4,
    package: "6LPA",
  },
  {
    sNo: 12,
    company: "CHIC MIC",
    programme: "B.Tech-CSE",
    sector: "IT",
    studentsPlaced: 4,
    package: "5LPA",
  },
  {
    sNo: 13,
    company: "COSMOFEED",
    programme: "B.Tech-CSE",
    sector: "IT",
    studentsPlaced: 2,
    package: "4.5LPA",
  },
  {
    sNo: 14,
    company: "CREST VENU AND ENTERTAINMENT SOFTWARE PVT.LTD(24/7)",
    programme: "B.Tech-CSE",
    sector: "IT",
    studentsPlaced: 5,
    package: "8LPA",
  },
  {
    sNo: 15,
    company: "CYBER SHINES TECHNOLOGIES PVT. LTD.",
    programme: "MCA",
    sector: "IT",
    studentsPlaced: 4,
    package: "5LPA",
  },
  {
    sNo: 16,
    company: "DE FACTO INFOTECH",
    programme: "B.Tech-CSE",
    sector: "IT",
    studentsPlaced: 4,
    package: "3LPA",
  },
  {
    sNo: 17,
    company: "DEEPMINDZ INNOVATIONS PRIVATE LIMITED",
    programme: "B.Tech-CSE",
    sector: "IT",
    studentsPlaced: 3,
    package: "4LPA",
  },
  {
    sNo: 18,
    company: "DEV TRADERS",
    programme: "BCA",
    sector: "IT",
    studentsPlaced: 4,
    package: "2.4 LPA",
  },
  {
    sNo: 19,
    company: "DEVLANCE",
    programme: "B.Tech-CSE",
    sector: "IT",
    studentsPlaced: 3,
    package: "4LPA",
  },
  {
    sNo: 20,
    company: "DHARMA CONSULTANCY PVT LTD",
    programme: "B.Tech-CSE",
    sector: "Marketing",
    studentsPlaced: 3,
    package: "3.5LPA",
  },
  {
    sNo: 21,
    company: "DIXON ELECTRONICS SELAQUI",
    programme: "B.Tech-ECE,EEE",
    sector: "Manufacturing",
    studentsPlaced: 4,
    package: "3.5LPA",
  },
  {
    sNo: 22,
    company: "DUNZO DIGITAL PVT. LTD.",
    programme: "MCA",
    sector: "Marketing",
    studentsPlaced: 4,
    package: "8LPA",
  },
  {
    sNo: 23,
    company: "ECO TECH CIVIL CONSULTANT",
    programme: "B.Tech-Civil,Poly",
    sector: "Civil Construction",
    studentsPlaced: 3,
    package: "3LPA",
  },
  {
    sNo: 24,
    company: "ENQUO SOLUTION PVT. LTD",
    programme: "B.Tech-CSE",
    sector: "IT",
    studentsPlaced: 3,
    package: "3LPA",
  },
  {
    sNo: 25,
    company: "ESAYOG NEPAL PVT LTD",
    programme: "B.Tech-CSE",
    sector: "Construction",
    studentsPlaced: 2,
    package: "3LPA",
  },
  {
    sNo: 26,
    company: "EVENTIRON INDIA PVT.LTD.",
    programme: "B.Tech-CSE",
    sector: "Construction",
    studentsPlaced: 2,
    package: "3LPA",
  },
  {
    sNo: 27,
    company: "EVOKE",
    programme: "B.Tech-CSE",
    sector: "IT",
    studentsPlaced: 3,
    package: "3.5LPA",
  },
  {
    sNo: 28,
    company: "EXTRA MARKS NOIDA",
    programme: "B.Tech ALL Branch",
    sector: "Marketing",
    studentsPlaced: 6,
    package: "6LPA",
  },
  {
    sNo: 29,
    company: "FETELO",
    programme: "MCA",
    sector: "IT",
    studentsPlaced: 4,
    package: "5LPA",
  },
  {
    sNo: 30,
    company: "FLORANET",
    programme: "B.Tech-CSE",
    sector: "IT",
    studentsPlaced: 2,
    package: "5LPA",
  },
  {
    sNo: 31,
    company: "HACHIWEB",
    programme: "B.Tech-Civil",
    sector: "IT",
    studentsPlaced: 1,
    package: "4LPA",
  },
  {
    sNo: 32,
    company: "HEXAWARE",
    programme: "B.Tech-CSE,ECE",
    sector: "IT",
    studentsPlaced: 4,
    package: "6LPA",
  },
  {
    sNo: 33,
    company: "HIKE EDUCATION",
    programme: "B.Tech ALL Branch",
    sector: "Marketing",
    studentsPlaced: 6,
    package: "6LPA",
  },
  {
    sNo: 34,
    company: "IDEA FOUNDATION",
    programme: "B.Tech-CSE,BCA",
    sector: "IT",
    studentsPlaced: 4,
    package: "5LPA",
  },
  {
    sNo: 35,
    company: "ISUWA ENERGY PVT LTD.",
    programme: "B.Tech-Civil",
    sector: "Manufacturing",
    studentsPlaced: 1,
    package: "3.5LPA",
  },
  {
    sNo: 36,
    company: "J. KUMAR INFRAPROJECT PVT LTD",
    programme: "B.Tech-Civil,Poly",
    sector: "Civil Construction",
    studentsPlaced: 2,
    package: "3.5LPA",
  },
  {
    sNo: 37,
    company: "JIO PLATFORMS LIMITED",
    programme: "B.Tech-CSE,ECE",
    sector: "IT",
    studentsPlaced: 3,
    package: "7LPA",
  },
  {
    sNo: 38,
    company: "LG SOFT INDIA",
    programme: "B.Tech-CSE,ECE",
    sector: "IT",
    studentsPlaced: 3,
    package: "6LPA",
  },
  {
    sNo: 39,
    company: "M/S ESET CONSULTANCY & ALLIED",
    programme: "B.Tech-Civil,Poly",
    sector: "Civil Construction",
    studentsPlaced: 3,
    package: "4LPA",
  },
  {
    sNo: 40,
    company: "M/S KAMENG INFRA",
    programme: "B.Tech-Civil",
    sector: "Construction",
    studentsPlaced: 2,
    package: "4LPA",
  },
  {
    sNo: 41,
    company: "MILESTONE",
    programme: "B.Tech-CSE",
    sector: "Construction",
    studentsPlaced: 2,
    package: "3.5LPA",
  },
  {
    sNo: 42,
    company: "MIRAE CONSTRUCTION INDIA PVT LTD",
    programme: "B.Tech-Civil",
    sector: "Construction",
    studentsPlaced: 2,
    package: "3.5LPA",
  },
  {
    sNo: 43,
    company: "MKC INFRA",
    programme: "B.Tech-Civil,ME,Poly ME",
    sector: "Construction",
    studentsPlaced: 7,
    package: "3.5LPA",
  },
  {
    sNo: 44,
    company: "MULTI BUILDERS PVT LTD",
    programme: "B.Tech-Civil",
    sector: "Construction",
    studentsPlaced: 1,
    package: "3.5LPA",
  },
  {
    sNo: 45,
    company: "NAEHAS SOFTWARE INDIA PROVATE LIMITED",
    programme: "B.Tech-CSE",
    sector: "IT",
    studentsPlaced: 4,
    package: "8LPA",
  },
  {
    sNo: 46,
    company: "NIGLA INFRASTRUCTURE & POWER PROJECT LTD",
    programme: "B.Tech-Civil",
    sector: "Construction",
    studentsPlaced: 1,
    package: "3LPA",
  },
  {
    sNo: 47,
    company: "NUCLEUS SOFTWARE EXPORTS LIMITED",
    programme: "B.Tech-CSE,MCA,BCA",
    sector: "IT",
    studentsPlaced: 2,
    package: "5LPA",
  },
  {
    sNo: 48,
    company: "OGON SOFTWARE",
    programme: "B.Tech-CSE",
    sector: "IT",
    studentsPlaced: 2,
    package: "4.5LPA",
  },
  {
    sNo: 49,
    company: "ORBIT CONSTRUCTION PVT LTD",
    programme: "B.Tech-Civil",
    sector: "Construction",
    studentsPlaced: 1,
    package: "3.8LPA",
  },
  {
    sNo: 50,
    company: "PARADOX ALPHA FOUNDATION",
    programme: "BCA",
    sector: "IT",
    studentsPlaced: 6,
    package: "2.5LPA",
  },
  {
    sNo: 51,
    company: "R & R BROTHER CONSTRUCTION",
    programme: "B.Tech-Civil",
    sector: "Construction",
    studentsPlaced: 1,
    package: "3.8LPA",
  },
  {
    sNo: 52,
    company: "RIYA CONSULTING PVT LTD",
    programme: "B.Tech-Civil",
    sector: "Construction",
    studentsPlaced: 1,
    package: "3.8LPA",
  },
  {
    sNo: 53,
    company: "SEASIA",
    programme: "B.Tech-CSE,BCA",
    sector: "IT",
    studentsPlaced: 2,
    package: "3.5LPA",
  },
  {
    sNo: 54,
    company: "SHEETAL ENTERPRISES",
    programme: "B.Tech-CSE",
    sector: "IT",
    studentsPlaced: 3,
    package: "5LPA",
  },
  {
    sNo: 55,
    company: "SHOR VALLEY PVT LTD",
    programme: "B.Tech-CSE",
    sector: "IT",
    studentsPlaced: 2,
    package: "4LPA",
  },
  {
    sNo: 56,
    company: "SHRI RAJENDRA KUMAR KALAL CONSTRUCTION LTD",
    programme: "B.Tech-Civil",
    sector: "Construction",
    studentsPlaced: 1,
    package: "3.8LPA",
  },
  {
    sNo: 57,
    company: "SKILL VERTEX",
    programme: "B.Tech-Civil",
    sector: "IT",
    studentsPlaced: 1,
    package: "4LPA",
  },
  {
    sNo: 58,
    company: "SKYLARK FEED HARYANA",
    programme: "B.Tech-ME,EEE",
    sector: "Manufacturing",
    studentsPlaced: 3,
    package: "4LPA",
  },
  {
    sNo: 59,
    company: "SOLITAIRE INFOSYS PVT. LTD.",
    programme: "B.Tech-CSE",
    sector: "IT",
    studentsPlaced: 4,
    package: "3.5LPA",
  },
  {
    sNo: 60,
    company: "SOPRA STERIA",
    programme: "B.Tech-CSE",
    sector: "IT",
    studentsPlaced: 2,
    package: "3LPA",
  },
  {
    sNo: 61,
    company: "SUNCITY SHEETS",
    programme: "B.Tech-ME",
    sector: "Manufacturing",
    studentsPlaced: 4,
    package: "3LPA",
  },
  {
    sNo: 62,
    company: "TALENT O MIND",
    programme: "B.Tech-CSE,BCA,MCA",
    sector: "IT",
    studentsPlaced: 3,
    package: "3LPA",
  },
  {
    sNo: 63,
    company: "TARSY TECH PVT. LTD.",
    programme: "B.Tech-CSE",
    sector: "IT",
    studentsPlaced: 3,
    package: "4LPA",
  },
  {
    sNo: 64,
    company: "TEKNOEXPERTS",
    programme: "B.Tech-CSE",
    sector: "IT",
    studentsPlaced: 5,
    package: "4LPA",
  },
  {
    sNo: 65,
    company: "THIAGRAJ CO",
    programme: "B.Tech-CSE",
    sector: "IT",
    studentsPlaced: 3,
    package: "4.5LPA",
  },
  {
    sNo: 66,
    company: "TOUCH SYSTEM",
    programme: "B.Tech-CSE",
    sector: "IT",
    studentsPlaced: 4,
    package: "3.5LPA",
  },
  {
    sNo: 67,
    company: "V-DAWN PVT. LTD.",
    programme: "B.Tech-CSE",
    sector: "IT",
    studentsPlaced: 4,
    package: "3LPA",
  },
  {
    sNo: 68,
    company: "VIVADOM",
    programme: "B.Tech-CSE",
    sector: "IT",
    studentsPlaced: 2,
    package: "3.5LPA",
  },
  {
    sNo: 69,
    company: "XINRAY TECHNOLOGIES",
    programme: "B.Tech-CSE",
    sector: "IT",
    studentsPlaced: 2,
    package: "5LPA",
  },
  {
    sNo: 70,
    company: "ZENTECH",
    programme: "B.Tech-CSE",
    sector: "IT",
    studentsPlaced: 3,
    package: "3.5LPA",
  },
  {
    sNo: 71,
    company: "ZETTALOGICS",
    programme: "B.Tech-CSE",
    sector: "IT",
    studentsPlaced: 4,
    package: "3LPA",
  },
  {
    sNo: 72,
    company: "ZYNGA",
    programme: "B.Tech-CSE",
    sector: "IT",
    studentsPlaced: 3,
    package: "6LPA",
  },
  {
    sNo: 73,
    company: "ORACLE",
    programme: "B.Tech-CSE",
    sector: "IT",
    studentsPlaced: 4,
    package: "9LPA",
  },
  {
    sNo: 74,
    company: "VIRTUAL STONE",
    programme: "B.Tech-CSE",
    sector: "IT",
    studentsPlaced: 4,
    package: "3.5LPA",
  },
  {
    sNo: 75,
    company: "UBER",
    programme: "B.Tech-CSE",
    sector: "IT",
    studentsPlaced: 4,
    package: "6LPA",
  },
  {
    sNo: 76,
    company: "TCS",
    programme: "B.Tech-CSE,EEE,ME",
    sector: "IT",
    studentsPlaced: 10,
    package: "6.5LPA",
  },
  {
    sNo: 77,
    company: "SAP",
    programme: "B.Tech-CSE",
    sector: "IT",
    studentsPlaced: 4,
    package: "7LPA",
  },
  {
    sNo: 78,
    company: "WIPRO",
    programme: "B.Tech-CSE,IT",
    sector: "IT",
    studentsPlaced: 8,
    package: "6LPA",
  },
  {
    sNo: 79,
    company: "INFOSYS",
    programme: "B.Tech-CSE",
    sector: "IT",
    studentsPlaced: 6,
    package: "6LPA",
  },
  {
    sNo: 80,
    company: "L&T",
    programme: "B.Tech-CSE",
    sector: "IT",
    studentsPlaced: 7,
    package: "7LPA",
  },
  {
    sNo: 81,
    company: "ACCENTURE",
    programme: "B.Tech-CSE",
    sector: "IT",
    studentsPlaced: 5,
    package: "7LPA",
  },
  {
    sNo: 82,
    company: "MINDTREE",
    programme: "B.Tech-CSE",
    sector: "IT",
    studentsPlaced: 3,
    package: "7LPA",
  },
  {
    sNo: 83,
    company: "HEXAVARSITY",
    programme: "B.Tech-CSE",
    sector: "IT",
    studentsPlaced: 5,
    package: "4LPA",
  },
  {
    sNo: 84,
    company: "COGNIZANT",
    programme: "B.Tech-CSE",
    sector: "IT",
    studentsPlaced: 10,
    package: "6.5LPA",
  },
  {
    sNo: 85,
    company: "TCS",
    programme: "B.Tech-CSE",
    sector: "IT",
    studentsPlaced: 12,
    package: "7.5LPA",
  },
  {
    sNo: 86,
    company: "HCL",
    programme: "B.Tech-CSE",
    sector: "IT",
    studentsPlaced: 6,
    package: "6LPA",
  },
  {
    sNo: 87,
    company: "CAPGEMINI",
    programme: "B.Tech-CSE",
    sector: "IT",
    studentsPlaced: 8,
    package: "6LPA",
  },
  {
    sNo: 88,
    company: "MWIDM",
    programme: "B.Tech All Branch,BCA,MCA",
    sector: "IT",
    studentsPlaced: 6,
    package: "3.5LPA",
  },
  {
    sNo: 89,
    company: "Mobiloitte",
    programme: "CSE,MBA,BCA,MCA",
    sector: "IT",
    studentsPlaced: 6,
    package: "3LPA",
  },
];

export default tableData;
